branches:
  only:
    - jenkins-testing
    - test-branch
jobs:
  include:
    - stage: test
      script: 
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./Scripts/travis/test-macOS.sh; fi
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./Scripts/travis/test-Linux.sh; fi
    - stage: release new version
      script: ./Scripts/travis/new-release.sh
      os: osx
      if: branch = jenkins-testing
    - stage: deploy to cocoapods
      script: ./Scripts/travis/deploy-to-cocoapods.sh
      os: osx
      if: branch = jenkins-testing
    - stage: publish documentation
      script: ./Scripts/travis/publish-documentation.sh
      os: osx
      if: branch = jenkins-testing