matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9.3
branches:
  only:
    - master
    - develop
    - semantic-versioning
env:
  global:
    - IOS_SDK="iphonesimulator"
    - IOS_DESTINATION="OS=11.3,name=iPhone 7"
before_install:
  - sudo easy_install pip
  - npm install -g npm@6.x
install:
  - gem install cocoapods
  - pip install --user bumpversion
  - npm install @semantic-release/exec
script:
  - echo "Script"
deploy:
  - provider: script
    skip_cleanup: true
    script: npx travis-deploy-once "npx semantic-release"
    on:
      branch: semantic-versioning