# matrix:
#   include:
#     - os: linux
#       dist: trusty
#       sudo: required
#     - os: osx
#       osx_image: xcode10.1
os: osx
branches:
  only:
    - jenkins-testing
env:
  global:
    - IOS_SDK="iphonesimulator"
    - IOS_DESTINATION="name=iPhone XS,OS=12.0"
jobs:
  include:
    - stage: test
      script: ./Scripts/travis/test.sh
    - stage: deploy
      on:
        branch: jenkins-testing
        condition: $TRAVIS_OS_NAME = osx
      script: ./Scripts/travis/deploy.sh
    - stage: Publish Documentation
      on:
        branch: jenkins-testing
        condition: $TRAVIS_OS_NAME = osx