matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9.3
branches:
  only:
    - master
    - develop
    - semantic-versioning
env:
  global:
    - IOS_SDK="iphonesimulator"
    - IOS_DESTINATION="OS=11.3,name=iPhone 7"
before_install:
  - sudo easy_install pip
  - nvm install node
  - nvm use node
install:
  - gem install cocoapods
  - sudo pip install bumpversion
  - npm install -g semantic-release@15.9.0
  - npm install -g @semantic-release/exec
script:
  - echo "Script"
deploy:
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
    on:
      branch: semantic-versioning
      condition: $TRAVIS_OS_NAME = osx
